# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2024-2025 Anna <cyber@sysrq.in>

kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: fedorapython/fedora-python-tox:latest
    commands:
      - tox run
      - tox -c find-work-bugzilla run
      - tox -c find-work-pgo run
      - tox -c find-work-pkgcheck run
      - tox -c find-work-repology run
