# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2024 Anna <cyber@sysrq.in>

kind: pipeline
type: docker
name: default

workspace:
  path: /tests

steps:
  - name: test
    image: 31z4/tox:4-5
    user: root
    commands:
      - tox run
      - tox -c find-work-bugzilla run
      - tox -c find-work-pgo run
      - tox -c find-work-pkgcheck run
      - tox -c find-work-repology run
