.\" SPDX-FileType: DOCUMENTATION
.\" SPDX-FileCopyrightText: 2024 Anna <cyber@sysrq.in>
.\" SPDX-License-Identifier: WTFPL
.\" No warranty
.Dd December 2, 2024
\" .Dt FIND-WORK-EXAMPLE 1
.Os
.Sh NAME
\" .Nm "find-work example"
\" .Nd discover ebuilds to improve using ...
.Sh SYNOPSIS
.Nm
\" Plugin-specific options
.Ar command
\" .Op Ar arg ...
.Sh DESCRIPTION
.Nm
is a module for
.Xr find-work 1
\" that uses <...> to find work.
.Pp
.
The options for
.Nm
are as follows:
.Bl -tag -width Ds
.\" Plugin-specific options, e.g.:
.\" .Fl r Ar repo , Fl -repo Ar repo
.
.El
.Pp
.
.Ar command
can be one of the following:
.Bl -tag -width Ds -offset indent
.\" Plugin commands, e.g:
.\" .It Ic command
.\" .Dl Pq alias: Ic cmd , Ic c
.\" .Pp
.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
\" Find outdated GURU packages installed on your system:
\" .Pp
\" .Dl "$ find-work -I repology -r gentoo_ovl_guru outdated"
.Sh AUTHORS
.An -nosplit
The
.Nm find-work
utility was written by
.An Anna Aq Mt cyber@sysrq.in .
